<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Outlet.Registry.Builder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Outlet.Core.Infrastructure/Outlet.Core.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Kernel.Shared/Outlet.Kernel.Shared/Outlet.Kernel.Shared.csproj" />
  </ItemGroup>

</Project>
